### ISSUE TITLE
[RE-DESIGN] Re-design the main concept of this repository

### ISSUE THREAD

**Issue by minayu416** [minayu416/iot-devices-gateway-data-processor#8]
## Description
I implemented two IOT-related products in last company, now I want to use one repository to perform and integrate all features in two products.

## Todo Parts

Main program implement

- [ ] Data gateway processor (receive data and send data via MQTT broker)
- [ ] DashBoard Back-end part (calculate data and integrate data then post to result)

Details Part

- [ ] Simulate receiving instant data
- [ ] Simulation data generator
- [ ] Calculate data
- [ ] Dash Board: show data
- [ ] Send/ Control commands to IoT devices
